config/routes.rb
#encoding: utf-8
Blog::Application.routes.draw do
  # main page
  root :to => 'principal#index'
  
  # devise routes
  devise_for :users, path_names: {sign_in: 'entrar', sign_out: 'sair'},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

  # active admin routes
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  # pag_seguro routes
  resources :matriculas
  resources :notificacoes
  
  # general routes
  resources :cursos do
    resources :interesses
    post "/enviar_mensagem", to: "admin::cursos#enviar_mensagem"
  end
  
  get "principal/sobre", as: :sobre
  get "/detalhes/:id", to: 'principal#detalhe', as: :detalhe_curso
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  def index
  end
  
  def sobre
  end
  
  def detalhe
    @curso = Curso.find(params[:id])
  end
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/views/principal/_curso.html.haml
%li{:class=>"panel radius curso_item"}
  %h3= link_to curso.nome, detalhe_curso_path(curso)
  %p{:class=>"text-center"}
    = link_to(detalhe_curso_path(curso)) do
      = image_tag curso.imagem_url(:main_page_thumb) if curso.imagem? 
  %p{:class=>"text-center"}
    - if user_signed_in?
      - if curso.matriculado?(current_user) 
        = link_to(url_for(curso), :class => "button round small success") do
          %i{:class => "foundicon-address-book"} &nbsp;Entrar
      - else
        - if curso.inicio_previsto
          = form_for(Matricula.new) do |f|
            = f.hidden_field :curso_id, :value => curso.id
            = button_tag(type: 'submit', class: "button round small") do
              %i{:class => "foundicon-cart"} &nbsp;Matricule-se
            = link_to(detalhe_curso_path(curso), class: "button round small") do 
              %i{:class => "foundicon-plus"} &nbsp;Ver Mais
        - else 
          = link_to(curso_interesses_path(curso), class: "button round small success", method: :post) do
            %i{:class => "foundicon-smiley"} &nbsp;Estou Interessado
          = link_to(detalhe_curso_path(curso), class: "button round small") do
            %i{:class => "foundicon-plus"} &nbsp;Ver Mais
    - else
      - if curso.inicio_previsto
        = link_to(new_user_session_path, :class => "button round small") do
          %i{:class => "foundicon-page"} &nbsp;Registre-se
      - else
        = link_to(curso_interesses_path(curso), class: "button round small success", method: :post) do
          %i{:class => "foundicon-smiley"} &nbsp;Estou Interessado
      = link_to(detalhe_curso_path(curso), class: "button round small") do
        %i{:class => "foundicon-plus"} &nbsp;Ver Mais

app/views/principal/detalhe.html.erb
<div class="large-8 columns panel" role="content">
  <h3><%= @curso.nome %></h3>

  <div class="row">
    <div class="large-6 columns">
      <%= image_tag @curso.imagem_url(:thumb) if @curso.imagem? %>
    </div>
    <div class="large-6 columns">
      <p><%= @curso.descricao %></p>
    </div>
  </div>
  <hr/>
  <div class="row">
    <div class="large-9 columns">
      <div data-alert="" class="alert-box success round">
        Valor: <%= em_reais(@curso.preco) %>
      </div>
    </div>
    <div class="large-3 columns">
      <% if user_signed_in? %>
        <% if @curso.matriculado?(current_user) %>
          <%= link_to(url_for(@curso), :class => "button round small success") do %>
            <i class="foundicon-address-book"></i>&nbsp;Entrar
          <% end %>
        <% else %>
          <% if @curso.inicio_previsto %>
            <%= form_for(Matricula.new) do |f| %>
              <%= f.hidden_field :curso_id, :value => @curso.id %>
              <%= button_tag(type: 'submit', class: "button round small") do %>
                <i class="foundicon-cart"></i>&nbsp;Matricule-se</a>&nbsp;
              <% end %>
            <% end %>
          <% else %>
            <div data-alert="" class="alert-box">
              Este curso ainda não tem início previsto.
            </div>
          <% end %>
        <% end %>
      <% else %>
        <% if @curso.inicio_previsto %>
          <%= link_to(new_user_session_path, :class => "button round small") do %>
            <i class="foundicon-page"></i>&nbsp;Registre-se
          <% end %>
        <% else %>
          <div data-alert="" class="alert-box">
            Este curso ainda não tem início previsto.
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<aside class="large-4 columns panel">
  <h3>Ementa</h3>
  <p><%= @curso.ementa.html_safe %></p>
</aside>

app/views/principal/index.html.haml
%div{:class => "large-9 columns", :role => "content"}
  %h4{:class =>"text-center faixa"} Turmas Abertas
  %ul{:class=>"small-block-grid-2 large-block-grid-2"}
    - Curso.abertos.each do |curso| 
      = render :partial => "curso", :locals => {:curso => curso}
  %hr
  %h4{:class =>"text-center faixa"} Próximas Turmas
  %ul{:class=>"small-block-grid-2 large-block-grid-2"}
    - Curso.proximos.each do |curso| 
      = render :partial => "curso", :locals => {:curso => curso}
= render :partial => "partials/sidebar"

app/views/principal/sobre.html.erb
<div class="large-9 columns" role="content">
  <article>
    <ul data-orbit data-options="timer_speed:2500">
      <li>
        <%= image_tag "distancia.jpg" %>
        <div class="orbit-caption">Cursos de extensão a distância</div>
      </li>
      <li>
        <%= image_tag "meu.jpg" %>
        <div class="orbit-caption">Todo o material do curso é SEU !</div>
      </li>
      <li>
        <%= image_tag "hangouts.jpg" %>
        <div class="orbit-caption">Acompanhamento ao vivo via Hangouts</div>
      </li>
      <li>
        <%= image_tag "correios.jpg" %>
        <div class="orbit-caption">Certificado enviado a sua residência após o curso</div>
      </li>
      <li>
        <%= image_tag "duvidas.jpg" %>
        <div class="orbit-caption">Tira-dúvidas através de fóruns online</div>
      </li>
      <li>
        <%= image_tag "pagseguro.jpg" %>
        <div class="orbit-caption">Pagamento através do PagSeguro</div>
      </li>
    </ul>    
  </article>
</div>
<!-- Sidebar -->
<aside class="large-3 columns panel">
  <h5>Cursos</h5>
  <ul class="side-nav">
    <% Curso.all.each do |curso| %>
      <li><%= link_to curso.nome, detalhe_curso_path(curso) %></li>
    <% end %>
  </ul>
</aside>
<!-- End Sidebar -->