config/routes.rb
#encoding: utf-8
Blog::Application.routes.draw do
  # main page
  root :to => 'principal#index'
  
  # devise routes
  devise_for :users, path_names: {sign_in: 'entrar', sign_out: 'sair'},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

  # active admin routes
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  # pag_seguro routes
  resources :matriculas
  resources :notificacoes
  
  # general routes
  resources :cursos do
    resources :interesses
    post "/enviar_mensagem", to: "admin::cursos#enviar_mensagem"
  end
  
  get "principal/sobre", as: :sobre
  get "/detalhes/:id", to: 'principal#detalhe', as: :detalhe_curso
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/aula.rb
class Aula < ActiveRecord::Base
  belongs_to :curso
  attr_accessible :descricao, :nome, :url, :curso, :curso_id, :video
end

app/models/curso.rb
class Curso < ActiveRecord::Base
  extend FriendlyId
  
  # Atributos transientes
  attr_accessor :mensagem
  
  # Atributos especiais
  friendly_id :nome, use: :slugged
  mount_uploader :imagem, ImagemUploader
  
  attr_accessible :descricao, :imagem, :inicio_previsto, :nome, :proxima_turma
  attr_accessible :preco, :ementa, :tem_promocao, :preco_promocional, :aviso
  
  # Relacionamentos
  has_many :matriculas
  has_many :materiais
  has_many :aulas
  has_many :hangouts
  
  # Geração dos slugs
  def slug_candidates
    [
      :nome,
      [:nome, :id]
    ]
  end
  
  def matriculado?(user)
    matriculas.where("user_id = ? AND estado_cd = ?", user.id, Matricula.estados(:confirmada)).exists?
  end
  
  def to_s
    nome
  end
  
  scope :abertos,  -> { where(inicio_previsto: true).order("proxima_turma, id") }
  scope :proximos, -> { where(inicio_previsto: false).order("created_at") }
end

app/models/hangout.rb
class Hangout < ActiveRecord::Base
  belongs_to :curso
  attr_accessible :descricao, :nome, :url, :curso, :curso_id, :video
end

app/models/interesse.rb
class Interesse < ActiveRecord::Base
  belongs_to :curso
  belongs_to :user
  
  attr_accessible :curso, :user, :curso_id, :user_id
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :curso
  attr_accessible :descricao, :nome, :url, :curso, :curso_id
end

app/models/matricula.rb
class Matricula < ActiveRecord::Base
  belongs_to :curso
  belongs_to :user
  attr_accessible :estado_cd, :curso_id, :user_id, :estado
  
  as_enum :estado, :reservada => 0, :confirmada => 1, :cancelada => 2
  
  def promocao?
    Matricula.where("user_id = ? AND estado_cd = ?", user.id, Matricula.estados(:confirmada)).exists?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :identifier
  # attr_accessible :title, :body

  validates_presence_of :username
  
  has_many :matriculas
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.email    = auth.info.email
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end  
  
  def to_s
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def facebook
    return unless session['oauth_token']
    session['fb_user'] ||= FbGraph::User.me(session['oauth_token']).fetch
  end
  helper_method :facebook
  
  def get_facebook_user(username)
    FbGraph::User.fetch(username)
  end
  helper_method :get_facebook_user
  
  def set_locale
    I18n.locale = :"pt-BR"
  end
  before_filter :set_locale
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @matriculas = Matricula.where("user_id = ? AND estado_cd = ?", current_user, Matricula.estados(:confirmada)).order("created_at DESC")
  end
  
  def show
    @curso = Curso.find(params[:id])
  end
end

app/controllers/interesses_controller.rb
#encoding: utf-8
class InteressesController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    curso = Curso.find(params[:curso_id])
    
    if Interesse.where("curso_id = ? AND user_id = ?", curso, current_user).exists?
      redirect_to "/", alert: "Seu interesse neste curso já foi registrado"
    else
      Interesse.create!(curso: curso, user: current_user)
      redirect_to "/", notice: "Obrigado, seu interesse neste curso foi registrado"
    end
  end
end

app/controllers/matriculas_controller.rb
class MatriculasController < ApplicationController
  before_filter :authenticate_user!
  
  def create
    @matricula        = Matricula.new(params[:matricula])
    @matricula.user   = current_user
    @matricula.estado = :reservada
    @matricula.save!
    
    preco = @matricula.curso.preco
    if @matricula.promocao? and @matricula.curso.tem_promocao
      preco = @matricula.curso.preco_promocional
    end

    payment = PagSeguro::Payment.new('brunogamacatao@gmail.com', '8AE446E9204345D4B571A0C7CFFA9CC1', id: @matricula.id)
    payment.items = [
      PagSeguro::Item.new(id: @matricula.curso.id, 
                          description: @matricula.curso.nome, 
                          amount: preco,  
                          quantity: "1")
    ]
    
    nome = facebook ? facebook.name : @matricula.user.username
    
    payment.sender   = PagSeguro::Sender.new(name: nome, email: current_user.email)
    payment.shipping = PagSeguro::Shipping.new(type: PagSeguro::Shipping::UNIDENTIFIED)
    
    redirect_to payment.checkout_payment_url
  end
end

app/controllers/notificacoes_controller.rb
class NotificacoesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  
  def index
    @notification_code = params[:id_pagseguro]
  end
  
  def create
    return unless request.post?
    
    email             = "brunogamacatao@gmail.com"
    token             = "8AE446E9204345D4B571A0C7CFFA9CC1"
    notification_code = params[:notificationCode]
    
    notification = PagSeguro::Notification.new(email, token, notification_code)
    matricula    = Matricula.find(notification.id)
    
    if notification.approved?
      matricula.estado = :confirmada
      MatriculaMailer.confirmacao(matricula).deliver
    elsif notification.cancelled? || notification.returned?
      matricula.estado = :cancelada
    end
    
    matricula.save!
    
    render :nothing => true
  end
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  def index
  end
  
  def sobre
  end
  
  def detalhe
    @curso = Curso.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def em_reais(valor)
    number_to_currency(valor, :unit => 'R$', :format => '%u %n', :separator => ',', :delimiter => '.')
  end
  
  def vimeo(video)
    html = <<-html
      <iframe src="#{video}" width="500" height="281" frameborder="0" 
        webkitallowfullscreen mozallowfullscreen allowfullscreen>
      </iframe>
    html
    html.html_safe
  end
  
  def youtube(video)
    html = <<-html
      <iframe width="420" height="315" src="#{video}" frameborder="0" allowfullscreen></iframe>
    html
    .html_safe
  end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/interesses_helper.rb
module InteressesHelper
end

app/helpers/matriculas_helper.rb
module MatriculasHelper
end

app/helpers/notificacoes_helper.rb
module NotificacoesHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/views/admin/_curso.html.haml
%link{:type => "text/css", :rel => "stylesheet", :href => "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css"}
:css
  li.wysihtml5 {
    list-style-type: none;
  }
  li.wysihtml5 .label {
    display: none;
  }
  .ui-front {
    z-index:1000000 !important; /* The default is 100. !important overrides the default. */
  }

%h1= "#{image_tag @curso.imagem_url(:mini_thumb) if @curso.imagem?} #{@curso.nome}".html_safe
%h3= @curso.descricao
%hr
%br
%h2 Alunos Matriculados
%table
  %thead
    %tr
      %th Usuário
      %th E-mail
      %th Estado
    - @curso.matriculas.each do |matricula|
      - if matricula.user
        %tr
          %td= matricula.user.username
          %td= matricula.user.email
          %td= matricula.estado.to_s.capitalize

#mensagem_dialog{title: "Enviar Mensagem"}
  = semantic_form_for([:admin, @curso], url: curso_enviar_mensagem_path(@curso), :html => {:method => :post}) do |f|
    = f.input :mensagem, as: :wysihtml5
    = f.submit "Enviar"

:javascript
  $(function() {
    $("#mensagem_dialog").dialog({
      width: 730,
      height: 350,
      modal: true,
      autoOpen: false
    });
    $("#link_enviar_msg").click(function(){
      $("#mensagem_dialog").dialog('open');
    });
  });

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
:plain
  <!--[if gt IE 8] -->
%html{:lang => "en"}
  /<![endif]
  %head
    %meta{:charset => "utf-8"}/
    
    / Set the viewport width to device width for mobile
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    
    %title= content_for?(:title) ? yield(:title) : "Bruno Catão"
    
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/custom.modernizr" 
    = csrf_meta_tags
  %body
    = render :partial => "partials/navbar"
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div{:class => "alert-box #{name == :notice ? "success" : "alert"}", :"data-alert" => true}
          = msg
          %a{:href => '#', :class => "close"} &times;
    .row= yield
    = render :partial => "partials/footer"
    = javascript_include_tag "application"

app/views/partials/_disqus.html.haml
#disqus_thread
:javascript
  var disqus_shortname  = 'brunocato';
  var disqus_developer  = #{ Rails.env == "production" ? '0' : '1' };
  var disqus_title      = "#{ title }";
  var disqus_identifier = "#{ request.fullpath }";

  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();

app/views/partials/_footer.html.haml
%footer{:class => "row"}
  %div{:class => "large-12 columns"}
    %hr
    .row
      %div{:class => "large-6 columns"}
        %p="&copy; Copyright BrunoCatao.com, todos os direitos reservados.".html_safe
      %div{:class => "large-6 columns"}

app/views/partials/_navbar.html.haml
.row
  %div{:class => "large-12 columns"}
    %div{:class => "nav-bar right"}
      %ul{:class => "button-group"}
        %li= link_to "Início", "/"
        %li= link_to "Blog", "http://brunocatao.wordpress.com", :target => "_blank"
        - if user_signed_in?
          %li="Oi #{facebook ? facebook.name : current_user.username}"
          %li= link_to "Meus Cursos", cursos_path
          %li= link_to "Sair", destroy_user_session_path, method: :delete
        - else 
          %li= link_to "Sobre", sobre_path
          %li= link_to "Entrar", new_user_session_path
          %li= link_to "Registrar", new_user_registration_path
          %li= link_to "Entre pelo Facebook", user_omniauth_authorize_path(:facebook), :class => "button small"
    %h1="Bruno Catão"
    %hr

app/views/partials/_sidebar.html.haml
%aside{:class => "large-3 columns panel"}
  %h5="Cursos"
  %ul{:class => "side-nav"}
    - Curso.all.each do |curso|
      %li= link_to curso.nome, detalhe_curso_path(curso)